/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const CorpusEntry = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'audioId' : IDL.Opt(IDL.Text),
  'addedBy' : UserId,
  'audioStorageId' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'category' : IDL.Text,
  'inpui' : IDL.Text,
  'english' : IDL.Text,
});
export const AdminSettings = IDL.Record({
  'qrCodeData' : IDL.Text,
  'adminPrincipals' : IDL.Vec(IDL.Text),
  'upiId' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'authorId' : UserId,
  'authorName' : IDL.Text,
  'entryId' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const Contributor = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'contributionCount' : IDL.Nat,
  'isVerified' : IDL.Bool,
});
export const ParallelUploadEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'submittedBy' : UserId,
  'timestamp' : Timestamp,
  'inpui' : IDL.Text,
  'english' : IDL.Text,
});
export const QueueEntry = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'submittedBy' : UserId,
  'isDuplicate' : IDL.Bool,
  'timestamp' : Timestamp,
  'inpui' : IDL.Opt(IDL.Text),
  'english' : IDL.Opt(IDL.Text),
});
export const Stats = IDL.Record({
  'totalFavorites' : IDL.Nat,
  'totalEntries' : IDL.Nat,
  'queueSize' : IDL.Nat,
  'activeContributors' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAdminPrincipal' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addBulkToQueue' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Opt(IDL.Text), IDL.Opt(IDL.Text))), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addChatMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'addCorpusEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addToQueue' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'approveParallelEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'approveQueueEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'autoSetFirstAdmin' : IDL.Func([], [], []),
  'awardBadge' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteChatMessage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteCorpusEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Opt(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'exportCorpus' : IDL.Func([], [IDL.Vec(CorpusEntry)], ['query']),
  'getAdminPrincipals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getContributors' : IDL.Func([], [IDL.Vec(Contributor)], ['query']),
  'getCorpusEntries' : IDL.Func([], [IDL.Vec(CorpusEntry)], ['query']),
  'getFavorites' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Contributor)], ['query']),
  'getPendingParallelEntries' : IDL.Func(
      [],
      [IDL.Vec(ParallelUploadEntry)],
      ['query'],
    ),
  'getPredictions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(CorpusEntry, IDL.Float64))],
      ['query'],
    ),
  'getQueue' : IDL.Func([], [IDL.Vec(QueueEntry)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerContributor' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'rejectParallelEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeAdminPrincipal' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeFromQueue' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'searchCorpus' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(CorpusEntry)],
      ['query'],
    ),
  'submitParallelEntries' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Nat],
      [],
    ),
  'submitPredictionFeedback' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'toggleFavorite' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateAdminSettings' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateCorpusEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const CorpusEntry = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'audioId' : IDL.Opt(IDL.Text),
    'addedBy' : UserId,
    'audioStorageId' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'category' : IDL.Text,
    'inpui' : IDL.Text,
    'english' : IDL.Text,
  });
  const AdminSettings = IDL.Record({
    'qrCodeData' : IDL.Text,
    'adminPrincipals' : IDL.Vec(IDL.Text),
    'upiId' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'authorId' : UserId,
    'authorName' : IDL.Text,
    'entryId' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const Contributor = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'contributionCount' : IDL.Nat,
    'isVerified' : IDL.Bool,
  });
  const ParallelUploadEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'submittedBy' : UserId,
    'timestamp' : Timestamp,
    'inpui' : IDL.Text,
    'english' : IDL.Text,
  });
  const QueueEntry = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'submittedBy' : UserId,
    'isDuplicate' : IDL.Bool,
    'timestamp' : Timestamp,
    'inpui' : IDL.Opt(IDL.Text),
    'english' : IDL.Opt(IDL.Text),
  });
  const Stats = IDL.Record({
    'totalFavorites' : IDL.Nat,
    'totalEntries' : IDL.Nat,
    'queueSize' : IDL.Nat,
    'activeContributors' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAdminPrincipal' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addBulkToQueue' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Opt(IDL.Text), IDL.Opt(IDL.Text))), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addChatMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'addCorpusEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addToQueue' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'approveParallelEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'approveQueueEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'autoSetFirstAdmin' : IDL.Func([], [], []),
    'awardBadge' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteChatMessage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteCorpusEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Opt(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'exportCorpus' : IDL.Func([], [IDL.Vec(CorpusEntry)], ['query']),
    'getAdminPrincipals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getContributors' : IDL.Func([], [IDL.Vec(Contributor)], ['query']),
    'getCorpusEntries' : IDL.Func([], [IDL.Vec(CorpusEntry)], ['query']),
    'getFavorites' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Contributor)], ['query']),
    'getPendingParallelEntries' : IDL.Func(
        [],
        [IDL.Vec(ParallelUploadEntry)],
        ['query'],
      ),
    'getPredictions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(CorpusEntry, IDL.Float64))],
        ['query'],
      ),
    'getQueue' : IDL.Func([], [IDL.Vec(QueueEntry)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerContributor' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'rejectParallelEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeAdminPrincipal' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeFromQueue' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'searchCorpus' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(CorpusEntry)],
        ['query'],
      ),
    'submitParallelEntries' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Nat],
        [],
      ),
    'submitPredictionFeedback' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'toggleFavorite' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateAdminSettings' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateCorpusEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };