/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSettings {
  'qrCodeData' : string,
  'adminPrincipals' : Array<string>,
  'upiId' : string,
}
export interface ChatMessage {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'authorId' : UserId,
  'authorName' : string,
  'entryId' : bigint,
  'timestamp' : Timestamp,
}
export interface Contributor {
  'id' : UserId,
  'name' : string,
  'joinedAt' : Timestamp,
  'contributionCount' : bigint,
  'isVerified' : boolean,
}
export interface CorpusEntry {
  'id' : bigint,
  'isApproved' : boolean,
  'tags' : Array<string>,
  'audioId' : [] | [string],
  'addedBy' : UserId,
  'audioStorageId' : [] | [string],
  'timestamp' : Timestamp,
  'category' : string,
  'inpui' : string,
  'english' : string,
}
export interface ParallelUploadEntry {
  'id' : bigint,
  'status' : string,
  'submittedBy' : UserId,
  'timestamp' : Timestamp,
  'inpui' : string,
  'english' : string,
}
export interface QueueEntry {
  'id' : bigint,
  'source' : string,
  'submittedBy' : UserId,
  'isDuplicate' : boolean,
  'timestamp' : Timestamp,
  'inpui' : [] | [string],
  'english' : [] | [string],
}
export interface Stats {
  'totalFavorites' : bigint,
  'totalEntries' : bigint,
  'queueSize' : bigint,
  'activeContributors' : bigint,
}
export type Timestamp = bigint;
export type UserId = string;
export interface _SERVICE {
  'addAdminPrincipal' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addBulkToQueue' : ActorMethod<
    [Array<[[] | [string], [] | [string]]>, string],
    bigint
  >,
  'addChatMessage' : ActorMethod<
    [bigint, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'addCorpusEntry' : ActorMethod<
    [string, string, string, Array<string>, [] | [string]],
    bigint
  >,
  'addToQueue' : ActorMethod<[[] | [string], [] | [string], string], bigint>,
  'approveParallelEntry' : ActorMethod<[bigint], boolean>,
  'approveQueueEntry' : ActorMethod<
    [bigint, string, string, string, Array<string>],
    bigint
  >,
  'autoSetFirstAdmin' : ActorMethod<[], undefined>,
  'awardBadge' : ActorMethod<[string], boolean>,
  'deleteChatMessage' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteCorpusEntry' : ActorMethod<
    [bigint],
    { 'ok' : [] | [string] } |
      { 'err' : string }
  >,
  'exportCorpus' : ActorMethod<[], Array<CorpusEntry>>,
  'getAdminPrincipals' : ActorMethod<[], Array<string>>,
  'getAdminSettings' : ActorMethod<[], AdminSettings>,
  'getChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getContributors' : ActorMethod<[], Array<Contributor>>,
  'getCorpusEntries' : ActorMethod<[], Array<CorpusEntry>>,
  'getFavorites' : ActorMethod<[string], Array<bigint>>,
  'getLeaderboard' : ActorMethod<[], Array<Contributor>>,
  'getPendingParallelEntries' : ActorMethod<[], Array<ParallelUploadEntry>>,
  'getPredictions' : ActorMethod<[string], Array<[CorpusEntry, number]>>,
  'getQueue' : ActorMethod<[], Array<QueueEntry>>,
  'getStats' : ActorMethod<[], Stats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerContributor' : ActorMethod<[string], boolean>,
  'rejectParallelEntry' : ActorMethod<[bigint], boolean>,
  'removeAdminPrincipal' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeFromQueue' : ActorMethod<[bigint], boolean>,
  'searchCorpus' : ActorMethod<[string, [] | [string]], Array<CorpusEntry>>,
  'submitParallelEntries' : ActorMethod<[Array<[string, string]>], bigint>,
  'submitPredictionFeedback' : ActorMethod<[bigint, string, boolean], boolean>,
  'toggleFavorite' : ActorMethod<[bigint, string], boolean>,
  'updateAdminSettings' : ActorMethod<[string, string], boolean>,
  'updateCorpusEntry' : ActorMethod<
    [bigint, string, string, string, Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];