/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = string;
export type Timestamp = bigint;
export interface Contributor {
    id: UserId;
    name: string;
    joinedAt: Timestamp;
    contributionCount: bigint;
    isVerified: boolean;
}
export interface ParallelUploadEntry {
    id: bigint;
    status: string;
    submittedBy: UserId;
    timestamp: Timestamp;
    inpui: string;
    english: string;
}
export interface QueueEntry {
    id: bigint;
    source: string;
    submittedBy: UserId;
    isDuplicate: boolean;
    timestamp: Timestamp;
    inpui?: string;
    english?: string;
}
export interface CorpusEntry {
    id: bigint;
    isApproved: boolean;
    tags: Array<string>;
    audioId?: string;
    addedBy: UserId;
    audioStorageId?: string;
    timestamp: Timestamp;
    category: string;
    inpui: string;
    english: string;
}
export interface Stats {
    totalFavorites: bigint;
    totalEntries: bigint;
    queueSize: bigint;
    activeContributors: bigint;
}
export interface ChatMessage {
    id: bigint;
    isDeleted: boolean;
    content: string;
    authorId: UserId;
    authorName: string;
    entryId: bigint;
    timestamp: Timestamp;
}
export interface AdminSettings {
    qrCodeData: string;
    adminPrincipals: Array<string>;
    upiId: string;
}
export interface backendInterface {
    addAdminPrincipal(principal: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addBulkToQueue(entries: Array<[string | null, string | null]>, source: string): Promise<bigint>;
    addChatMessage(entryId: bigint, authorName: string, content: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addCorpusEntry(inpui: string, english: string, category: string, tags: Array<string>, audioId: string | null): Promise<bigint>;
    addToQueue(inpui: string | null, english: string | null, source: string): Promise<bigint>;
    approveParallelEntry(id: bigint): Promise<boolean>;
    approveQueueEntry(id: bigint, inpui: string, english: string, category: string, tags: Array<string>): Promise<bigint>;
    autoSetFirstAdmin(): Promise<void>;
    awardBadge(contributorId: string): Promise<boolean>;
    deleteChatMessage(messageId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteCorpusEntry(id: bigint): Promise<{
        __kind__: "ok";
        ok: string | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    exportCorpus(): Promise<Array<CorpusEntry>>;
    getAdminPrincipals(): Promise<Array<string>>;
    getAdminSettings(): Promise<AdminSettings>;
    getChatMessages(entryId: bigint): Promise<Array<ChatMessage>>;
    getContributors(): Promise<Array<Contributor>>;
    getCorpusEntries(): Promise<Array<CorpusEntry>>;
    getFavorites(userId: string): Promise<Array<bigint>>;
    getLeaderboard(): Promise<Array<Contributor>>;
    getPendingParallelEntries(): Promise<Array<ParallelUploadEntry>>;
    getPredictions(text: string): Promise<Array<[CorpusEntry, number]>>;
    getQueue(): Promise<Array<QueueEntry>>;
    getStats(): Promise<Stats>;
    isCallerAdmin(): Promise<boolean>;
    registerContributor(name: string): Promise<boolean>;
    rejectParallelEntry(id: bigint): Promise<boolean>;
    removeAdminPrincipal(principal: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeFromQueue(id: bigint): Promise<boolean>;
    searchCorpus(searchTerm: string, category: string | null): Promise<Array<CorpusEntry>>;
    submitParallelEntries(entries: Array<[string, string]>): Promise<bigint>;
    submitPredictionFeedback(entryId: bigint, predictedTranslation: string, isCorrect: boolean): Promise<boolean>;
    toggleFavorite(entryId: bigint, userId: string): Promise<boolean>;
    updateAdminSettings(upiId: string, qrCodeData: string): Promise<boolean>;
    updateCorpusEntry(id: bigint, inpui: string, english: string, category: string, tags: Array<string>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CorpusEntry as _CorpusEntry, QueueEntry as _QueueEntry, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdminPrincipal(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminPrincipal(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminPrincipal(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addBulkToQueue(arg0: Array<[string | null, string | null]>, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkToQueue(to_candid_vec_n2(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkToQueue(to_candid_vec_n2(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async addChatMessage(arg0: bigint, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatMessage(arg0, arg1, arg2);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatMessage(arg0, arg1, arg2);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCorpusEntry(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCorpusEntry(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCorpusEntry(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addToQueue(arg0: string | null, arg1: string | null, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addToQueue(to_candid_opt_n4(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToQueue(to_candid_opt_n4(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async approveParallelEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveParallelEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveParallelEntry(arg0);
            return result;
        }
    }
    async approveQueueEntry(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.approveQueueEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveQueueEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async autoSetFirstAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.autoSetFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoSetFirstAdmin();
            return result;
        }
    }
    async awardBadge(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadge(arg0);
            return result;
        }
    }
    async deleteChatMessage(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatMessage(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatMessage(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCorpusEntry(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: string | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCorpusEntry(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCorpusEntry(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportCorpus(): Promise<Array<CorpusEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportCorpus();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportCorpus();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPrincipals(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipals();
            return result;
        }
    }
    async getAdminSettings(): Promise<AdminSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSettings();
            return result;
        }
    }
    async getChatMessages(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getContributors(): Promise<Array<Contributor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContributors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContributors();
            return result;
        }
    }
    async getCorpusEntries(): Promise<Array<CorpusEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCorpusEntries();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCorpusEntries();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(arg0: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites(arg0);
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<Contributor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getPendingParallelEntries(): Promise<Array<ParallelUploadEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingParallelEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingParallelEntries();
            return result;
        }
    }
    async getPredictions(arg0: string): Promise<Array<[CorpusEntry, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictions(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictions(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQueue(): Promise<Array<QueueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueue();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueue();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerContributor(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerContributor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerContributor(arg0);
            return result;
        }
    }
    async rejectParallelEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectParallelEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectParallelEntry(arg0);
            return result;
        }
    }
    async removeAdminPrincipal(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminPrincipal(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminPrincipal(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromQueue(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromQueue(arg0);
            return result;
        }
    }
    async searchCorpus(arg0: string, arg1: string | null): Promise<Array<CorpusEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCorpus(arg0, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCorpus(arg0, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitParallelEntries(arg0: Array<[string, string]>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitParallelEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitParallelEntries(arg0);
            return result;
        }
    }
    async submitPredictionFeedback(arg0: bigint, arg1: string, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPredictionFeedback(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPredictionFeedback(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleFavorite(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavorite(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavorite(arg0, arg1);
            return result;
        }
    }
    async updateAdminSettings(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminSettings(arg0, arg1);
            return result;
        }
    }
    async updateCorpusEntry(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCorpusEntry(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCorpusEntry(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CorpusEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CorpusEntry): CorpusEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_QueueEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueueEntry): QueueEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isApproved: boolean;
    tags: Array<string>;
    audioId: [] | [string];
    addedBy: _UserId;
    audioStorageId: [] | [string];
    timestamp: _Timestamp;
    category: string;
    inpui: string;
    english: string;
}): {
    id: bigint;
    isApproved: boolean;
    tags: Array<string>;
    audioId?: string;
    addedBy: UserId;
    audioStorageId?: string;
    timestamp: Timestamp;
    category: string;
    inpui: string;
    english: string;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        tags: value.tags,
        audioId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.audioId)),
        addedBy: value.addedBy,
        audioStorageId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.audioStorageId)),
        timestamp: value.timestamp,
        category: value.category,
        inpui: value.inpui,
        english: value.english
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    source: string;
    submittedBy: _UserId;
    isDuplicate: boolean;
    timestamp: _Timestamp;
    inpui: [] | [string];
    english: [] | [string];
}): {
    id: bigint;
    source: string;
    submittedBy: UserId;
    isDuplicate: boolean;
    timestamp: Timestamp;
    inpui?: string;
    english?: string;
} {
    return {
        id: value.id,
        source: value.source,
        submittedBy: value.submittedBy,
        isDuplicate: value.isDuplicate,
        timestamp: value.timestamp,
        inpui: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.inpui)),
        english: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.english))
    };
}
function from_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_CorpusEntry, number]): [CorpusEntry, number] {
    return [
        from_candid_CorpusEntry_n9(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [string];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_CorpusEntry, number]>): Array<[CorpusEntry, number]> {
    return value.map((x)=>from_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QueueEntry>): Array<QueueEntry> {
    return value.map((x)=>from_candid_QueueEntry_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CorpusEntry>): Array<CorpusEntry> {
    return value.map((x)=>from_candid_CorpusEntry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_tuple_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string | null, string | null]): [[] | [string], [] | [string]] {
    return [
        to_candid_opt_n4(_uploadFile, _downloadFile, value[0]),
        to_candid_opt_n4(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string | null, string | null]>): Array<[[] | [string], [] | [string]]> {
    return value.map((x)=>to_candid_tuple_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
